### ISSUE TITLE
Challenge submission: Simplified GTFS models for integrated urban and transport planning

### ISSUE THREAD

**Issue by FlaviaMLopes** [Rbanism/repro-challenge#3]
# Rbanism Reproducibility Challenge submission 

The submission consists of the following steps:

1. Fill in the project information in the form below;
2. Submit this issue by clicking on **Submit new issue** without deleting the text below;
3. Fill in the (self-)assessment checklist generated by the issue;
4. Submit a separate comment in the same issue with a statement on the level of reproducibility of your project. Make sure you elaborate especially on the challenges you encountered and the boxes that are not ticked in the checklist -- word limit: 300 words;
5. Add another comment letting @cforgaci know that the submission is ready for assessment.

## Project information
- Project title: Simplified GTFS models for integrated urban and transport planning
- Author(s): Flavia Lopes
- Type of work: Research project (postdoctoral)
- Status: work in progress 
- Link to the GitHub repository of the project: https://github.com/FlaviaMLopes/simplified_GTFSmodels.git

## (Self-)Assessment Checklist
The following checklist is used for the assessment of the level of reproducibility of your project. Note that the checklist serves as a tool to help you think about the reproducibility of the data analysis. Although many of the questions can be thought of as having a yes/no answer, we encourage you to see the questions as being open ended with the real question being, "What can I do to improve the status of my project on this bullet point?" With that in mind, you will never get 100% of the bullets right for your project, but you will always be improving.

### Organization
- [x] Are all data, code, results, and documentation housed within a monophyletic (i.e., within one root) folder structure?
- [x] Is the project folder structured to separate your data, code, documentation, and results?
- [ ] Can the project be run from the project's root folder?
- [x] Is the project under version control?
- [x] Do files use a consistent naming scheme that indicates what they contain?

### Workflow and automation
- [x] Is the workflow clearly documented (with or without code)?
- [ ] Is the workflow scripted, i.e., using code? 
- [x] Is the code well documented?
- [ ] Is the code modular, i.e., does it use functions?
- [ ] Are unit tests available for the code?
- [ ] Does the repository make use of continuous integration tools to insure internal reproducibility?

### Documentation
- [x] Is there a README file that indicates
  - [x] the purpose of the project, 
  - [x] who to contact with questions, 
  - [x] a map of the directory structure, and 
  - [x] a description of what software and hardware are needed to reproduce your workflow?
- [x] Are there README files in each folder describing the contents of the folder, and how they were acquired/generated?
- [x] Is there a CITATION file that tells users how to site the project, data, and code?
- [x] Does the project have a LICENSE file?
- [ ] Is the project's repository publicly available?

### Publication
- [ ] Are papers and reports from the project generated using literate programming tools so that results are not hard-coded?
- [ ] Does the project have a persistent identifier?

### Data
- [x] Is the data included or linked, with instructions on how to obtain the data?
- [ ] If data is not included, is this because it is not necessary or generated as part of the project?
- [ ] Are your raw data (if any) and processed data files separated?
- [ ] If data is not open:
  - [ ] Is it accessible via a protocol?
  - [ ] Is there synthetic data provided so the project can be run?
- [x] Is citation information available for the data?
- [x] Does the data use open formats, such as CSV and TXT?

### Software
- [x] Is there a list of dependencies? 
- [ ] Is a container available to run the project?
- [ ] Are the version numbers of every external application used in the process?
- [x] Does the project use only open software?

This list was inspired by the more extensive [Checklist Questions to stimulate thought about a Project's Reproducibility](https://github.com/datacarpentry/rr-intro/blob/gh-pages/checklist.md).

**Comment by FlaviaMLopes** [comment]
The *"Simplified GTFS Models for Integrated Urban and Transport Planning"* are designed to be a reproducible model. During the model building process, we prioritize open source databases and packages. The description and workflow are detailed in the README files and in the notebook. Our idea is that researchers and professionals around the world with access to a GTFS, or at least a detailed public transport schedule, can reproduce the model to promote a better integration between urban and transport planning, as well as, cities more sustainable.

**Comment by FlaviaMLopes** [comment]
The submission is ready for assessment.

**Comment by cforgaci** [comment]
Thank you for your submission @FlaviaMLopes!

**Comment by FlaviaMLopes** [comment]
Thank you for the great initiative! 
Best!
Flavia

**Comment by cforgaci** [comment]
@FlaviaMLopes, could you please invite @hugoledoux, one of our reviewers, to your repository?

**Comment by FlaviaMLopes** [comment]
It's done, @cforgaci! :)

**Comment by cforgaci** [comment]
@FlaviaMLopes, please also invite @rusne, the second reviewer, to your repository.

**Comment by FlaviaMLopes** [comment]
It's done!

**Comment by rusne** [comment]
Hi @FlaviaMLopes could you add me once again? I was late with accepting the invitation and it has expired in the meantime. Sorry about that!

**Comment by FlaviaMLopes** [comment]
No problem. It's done!

**Comment by cforgaci** [comment]
Hi, @FlaviaMLopes. Can you please email me at C.Forgaci@tudelft.nl, so that I can communicate with you about the next step via email?

**Comment by FlaviaMLopes** [comment]
Ok!

**Comment by cforgaci** [comment]
Challenge ended. Congrats on the prize! 🎉 Closing this issue.
