### ISSUE TITLE
Challenge submission: Social segregation through the lens of big data on human mobility

### ISSUE THREAD

**Issue by TheYuanLiao** [Rbanism/repro-challenge#4]
# Rbanism Reproducibility Challenge submission 

The submission consists of the following steps:

1. Fill in the project information in the form below;
2. Submit this issue by clicking on **Submit new issue** without deleting the text below;
3. Fill in the (self-)assessment checklist generated by the issue;
4. Submit a separate comment in the same issue with a statement on the level of reproducibility of your project. Make sure you elaborate especially on the challenges you encountered and the boxes that are not ticked in the checklist -- word limit: 300 words;
5. Add another comment letting @cforgaci know that the submission is ready for assessment.

## Project information
- Project title: Social segregation through the lens of big data on human mobility
- Author(s): Yuan Liao, Laura Alessandretti, Jorge Gil, Sonia Yeh
- Type of work: research project (pilot study)
- Status: work in progress
- Link to the GitHub repository of the project: https://github.com/MobiSegInsights/mobi-social-segregation-se

## (Self-)Assessment Checklist
The following checklist is used for the assessment of the level of reproducibility of your project. Note that the checklist serves as a tool to help you think about the reproducibility of the data analysis. Although many of the questions can be thought of as having a yes/no answer, we encourage you to see the questions as being open ended with the real question being, "What can I do to improve the status of my project on this bullet point?" With that in mind, you will never get 100% of the bullets right for your project, but you will always be improving.

### Organization
- [x] Are all data, code, results, and documentation housed within a monophyletic (i.e., within one root) folder structure?
- [x] Is the project folder structured to separate your data, code, documentation, and results?
- [x] Can the project be run from the project's root folder?
- [x] Is the project under version control?
- [x] Do files use a consistent naming scheme that indicates what they contain?

### Workflow and automation
- [ ] Is the workflow clearly documented (with or without code)?
- [x] Is the workflow scripted, i.e., using code? 
- [ ] Is the code well documented?
- [x] Is the code modular, i.e., does it use functions?
- [ ] Are unit tests available for the code?
- [ ] Does the repository make use of continuous integration tools to insure internal reproducibility?

### Documentation
- [x] Is there a README file that indicates
  - [x] the purpose of the project, 
  - [x] who to contact with questions, 
  - [ ] a map of the directory structure, and 
  - [ ] a description of what software and hardware are needed to reproduce your workflow?
- [ ] Are there README files in each folder describing the contents of the folder, and how they were acquired/generated?
- [ ] Is there a CITATION file that tells users how to site the project, data, and code?
- [x] Does the project have a LICENSE file?
- [x] Is the project's repository publicly available?

### Publication
- [ ] Are papers and reports from the project generated using literate programming tools so that results are not hard-coded?
- [ ] Does the project have a persistent identifier?

### Data
- [ ] Is the data included or linked, with instructions on how to obtain the data?
- [ ] If data is not included, is this because it is not necessary or generated as part of the project?
- [x] Are your raw data (if any) and processed data files separated?
- [ ] If data is not open:
  - [ ] Is it accessible via a protocol?
  - [ ] Is there synthetic data provided so the project can be run?
- [x] Is citation information available for the data?
- [ ] Does the data use open formats, such as CSV and TXT?

### Software
- [ ] Is there a list of dependencies? 
- [ ] Is a container available to run the project?
- [ ] Are the version numbers of every external application used in the process?
- [x] Does the project use only open software?

This list was inspired by the more extensive [Checklist Questions to stimulate thought about a Project's Reproducibility](https://github.com/datacarpentry/rr-intro/blob/gh-pages/checklist.md).

**Comment by TheYuanLiao** [comment]
This is a pilot study of an ongoing research project at its earliest stage. The main challenge arises from being an ongoing project, especially a very exploratory one with uncertainties regarding the idea, scope, and data limitations. The current repo needs more detailed documentation of each part, especially the directory structure, which may change in the future. 

Another major shortcoming is the need for well-established workflow and automation. The data flow needs to be clearly shown and controlled. We will learn more about continuous integration tools and more formal ways of having unit tests. 

The last thing yet to be improved is the list of dependencies, a container, and their versions. 

This data-driven, visual, and descriptive project is nearly halfway toward reproducibility. We appreciate this initiative to drive us to learn more about doing reproducible research and how to better contribute to the community.

**Comment by TheYuanLiao** [comment]
Hi, I just got reminded by Jorge about this initiative and came here realizing the close date had just passed. I understand if you are not able to review my late submission. Anyway, this submission is ready for assessment @cforgaci. Thanks for organizing this! We will continue improving it with the provided checklist and additional material.

**Comment by cforgaci** [comment]
Thank you @TheYuanLiao for your submission!

**Comment by cforgaci** [comment]
Hi, @TheYuanLiao. Can you please email me at C.Forgaci@tudelft.nl, so that I can communicate with you about the next step via email?

**Comment by cforgaci** [comment]
Challenge ended. Congrats on the prize! 🎉 Closing this issue.
